### ISSUE TITLE
Im a complete noob

### ISSUE THREAD

**Issue by Mystic6T** [brisequentin/projetvoltairesolver#1]
Hi, I do not know how to start that at all, I opened it on VS, downloaded chromedriver.exe but now I Don't know how to start it lol

Help apprecied please :)

Cordially

**Comment by Mystic6T** [comment]
Re,

Si je dis pas de bêtises t’es Français!

Enfaite j’ouvre le fichier dans VS Code, Puis après je sais pas quoi faire
😭

Le mar. 31 janv. 2023 à 13:22, brisequentin ***@***.***> a
écrit :

**Comment by Mystic6T** [comment]
> 

Do you have discord please? It would be easier for assist

**Comment by Mystic6T** [comment]
> Hi Mystic6T, could you provide me more information?
> 
> Here are some points that could help you in solving your problem :
> 
> * Make sure to read the readme file
> * Have you installed correctly the lib?
> * What is the prompt, when launching the file ? did you google it ?
> 
> I stay available for other questions, we can also exchange through discord if you are still having issues.
> 
> Quentin.

Could I please get your discord? Thanks

**Comment by brisequentin** [comment]
quent1#9315

**Comment by Mystic6T** [comment]
> 

It's not working :/ 
![image](https://user-images.githubusercontent.com/124043196/216124574-1f68f993-864a-4517-8c4f-2e1e9b038738.png)

**Comment by brisequentin** [comment]
Quent1#9315 woops
